# Generated by Django 2.1.4 on 2018-12-22 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cibling_web', '0002_post_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_url',
        ),
    ]
